CREATE TABLE [dbo].[orders] (
    [Id]                    UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [CustomerId]            UNIQUEIDENTIFIER NULL,
    [so_id]                 NVARCHAR (200)   NULL,
    [so_code]               INT              NOT NULL,
    [contract_required]     NVARCHAR (45)    NULL,
    [attached_contract]     NVARCHAR (200)   NULL,
    [customer_name]         NVARCHAR (200)   NULL,
    [order_name]            NVARCHAR (200)   NULL,
    [order_date]            DATETIME         NULL,
    [sales_id]              NVARCHAR (45)    NULL,
    [sales_name]            NVARCHAR (200)   NULL,
    [sourcing]              NVARCHAR (45)    NULL,
    [order_update]          NVARCHAR (200)   NULL,
    [status_order_1]        NVARCHAR (45)    NULL,
    [status_order_2]        NVARCHAR (45)    NULL,
    [vat]                   NVARCHAR (45)    NULL,
    [recei_info]            NVARCHAR (200)   NULL,
    [payment_status]        NVARCHAR (45)    NULL,
    [payment_method]        NVARCHAR (200)   NULL,
    [notes]                 NVARCHAR (2000)  NULL,
    [return_date]           DATE             NULL,
    [ex_delivery_date]      DATE             NULL,
    [reality_delivery_date] DATETIME         NULL,
    [reality_payment_date]  DATETIME         NULL,
    [bb_image]              NVARCHAR (200)   NULL,
    [lot_status]            NVARCHAR (50)    NULL,
    [invoice_status]        NVARCHAR (45)    NULL,
    [vat_price]             DECIMAL (18, 2)  DEFAULT ((0)) NOT NULL,
    [vat_not_include]       DECIMAL (18, 2)  DEFAULT ((0)) NOT NULL,
    [discount_percentage]   DECIMAL (18, 2)  DEFAULT ((0)) NULL,
    [discount]              DECIMAL (18, 2)  DEFAULT ((0)) NULL,
    [total_money]           DECIMAL (18, 5)  DEFAULT ((0)) NOT NULL,
    [payment]               DECIMAL (18, 5)  DEFAULT ((0)) NOT NULL,
    [lack]                  DECIMAL (18, 5)  DEFAULT ((0)) NOT NULL,
    [CreatedOn]             DATETIME2 (7)    NULL,
    [CreatedBy]             NVARCHAR (MAX)   NULL,
    [UpdatedOn]             DATETIME2 (7)    NULL,
    [UpdatedBy]             NVARCHAR (MAX)   NULL,
    [LastAccessed]          DATETIME2 (7)    NULL,
    [deleted]               INT              NULL,
    [IpAddress]             NVARCHAR (MAX)   NULL,
    [InvoiceType]           NVARCHAR (MAX)   NULL,
    [ParentId]              UNIQUEIDENTIFIER NULL,
    [MisaCode]              NVARCHAR (MAX)   NULL,
    [IsSyncMisa]            INT              NOT NULL,
    [Edited]                NVARCHAR (MAX)   NULL,
    CONSTRAINT [pk_Order] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_orders_customers_CustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[customers] ([Id])
);


GO
CREATE NONCLUSTERED INDEX [IX_orders_CustomerId]
    ON [dbo].[orders]([CustomerId] ASC);

