CREATE TABLE [dbo].[products] (
    [Id]                          UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [prd_code]                    NVARCHAR (200)   NULL,
    [prd_name]                    NVARCHAR (255)   NULL,
    [pro_group]                   NVARCHAR (200)   NOT NULL,
    [prd_types]                   NVARCHAR (50)    NULL,
    [prd_materials]               NVARCHAR (200)   NULL,
    [prd_htbm]                    NVARCHAR (200)   NULL,
    [prd_image_url]               NVARCHAR (500)   NULL,
    [prd_units]                   INT              NOT NULL,
    [PrdUnitName]                 NVARCHAR (MAX)   NULL,
    [prd_units_id]                NVARCHAR (200)   NULL,
    [prd_note]                    NVARCHAR (1000)  NULL,
    [prd_qualified]               NVARCHAR (45)    NULL,
    [prd_sell_price]              DECIMAL (18)     DEFAULT ((0)) NULL,
    [effective_date]              DATETIME         NULL,
    [approved_by]                 NVARCHAR (45)    NULL,
    [prd_status]                  SMALLINT         NULL,
    [prd_group_id]                INT              NOT NULL,
    [qc_tutorial]                 NVARCHAR (200)   NULL,
    [ranking_development]         NVARCHAR (45)    NULL,
    [person_development]          NVARCHAR (45)    NULL,
    [expected_sourcing_lead_time] NVARCHAR (45)    NULL,
    [prd_list_image]              NVARCHAR (1000)  NULL,
    [group_buy]                   NVARCHAR (100)   NULL,
    [qr_code]                     NVARCHAR (200)   NULL,
    [created]                     DATETIME         NULL,
    [updated]                     DATETIME         NULL,
    [user_init]                   INT              NULL,
    [user_upd]                    INT              NULL,
    [old_prd_sell_price]          NVARCHAR (50)    NULL,
    [CreatedOn]                   DATETIME2 (7)    NULL,
    [CreatedBy]                   NVARCHAR (MAX)   NULL,
    [UpdatedOn]                   DATETIME2 (7)    NULL,
    [UpdatedBy]                   NVARCHAR (MAX)   NULL,
    [LastAccessed]                DATETIME2 (7)    NULL,
    [deleted]                     INT              NULL,
    [IpAddress]                   NVARCHAR (MAX)   NULL,
    [MisaCode]                    NVARCHAR (200)   NULL,
    CONSTRAINT [pk_Product] PRIMARY KEY CLUSTERED ([Id] ASC)
);

