CREATE TABLE [dbo].[suppliers] (
    [Id]                UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [supplier_code]     NVARCHAR (500)   NULL,
    [supplier_name]     NVARCHAR (500)   NULL,
    [image]             NVARCHAR (500)   NULL,
    [supplier_addr]     NVARCHAR (255)   NULL,
    [wecare_contact]    NVARCHAR (45)    NULL,
    [supplier_source]   NVARCHAR (200)   NULL,
    [supplier_type]     NVARCHAR (45)    NULL,
    [supplier_products] INT              NULL,
    [supplier_status]   NVARCHAR (45)    NULL,
    [supplier_price]    NVARCHAR (45)    NULL,
    [supplier_service]  NVARCHAR (45)    NULL,
    [ar_policy]         NVARCHAR (100)   NULL,
    [ar_rating]         NVARCHAR (45)    NULL,
    [notes]             NVARCHAR (1000)  NULL,
    [supplier_persons]  NVARCHAR (200)   NULL,
    [supplier_phone]    NVARCHAR (30)    NULL,
    [supplier_email]    NVARCHAR (150)   NULL,
    [supplier_web]      NVARCHAR (200)   NULL,
    [bank_name]         NVARCHAR (20)    NULL,
    [number_bank]       NVARCHAR (200)   NULL,
    [created]           DATETIME         NULL,
    [updated]           DATETIME         NULL,
    [user_init]         INT              NULL,
    [user_upd]          INT              NULL,
    [deleted]           INT              NULL,
    [SourcingStaff]     NVARCHAR (200)   NULL,
    [MisaCode]          NVARCHAR (MAX)   NULL,
    [Branch]            NVARCHAR (MAX)   NULL,
    [Tax_Code]          NVARCHAR (MAX)   NULL,
    [CreatedBy]         NVARCHAR (MAX)   NULL,
    [CreatedOn]         DATETIME2 (7)    NULL,
    [IpAddress]         NVARCHAR (MAX)   NULL,
    [LastAccessed]      DATETIME2 (7)    NULL,
    [UpdatedBy]         NVARCHAR (MAX)   NULL,
    [UpdatedOn]         DATETIME2 (7)    NULL,
    CONSTRAINT [pk_Supplier] PRIMARY KEY CLUSTERED ([Id] ASC)
);

